In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_excel("Bookings-100000-Rows.xlsx")

In [4]:
df

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,2024-07-31 09:06:00,09:06:00,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,NaN,NaN,No,NaN,111,Cash,41,3.6,3.8,https://cdn-icons-png.flaticon.com/128/11409/1...
103020,2024-07-31 15:12:00,15:12:00,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,NaN,NaN,No,NaN,1097,UPI,17,4.3,3.3,https://cdn-icons-png.flaticon.com/128/16526/1...
103021,2024-07-31 13:59:00,13:59:00,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,NaN,NaN,No,NaN,2201,Cash,37,3.6,3.2,https://cdn-icons-png.flaticon.com/128/9983/99...
103022,2024-07-31 14:56:00,14:56:00,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,NaN,NaN,No,NaN,267,UPI,47,3.4,3.1,https://cdn-icons-png.flaticon.com/128/6839/68...
103023,2024-07-31 13:57:00,13:57:00,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,NaN,NaN,No,NaN,462,UPI,3,4.8,4.4,https://cdn-icons-png.flaticon.com/128/16526/1...

In [5]:
df.drop_duplicates()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,2024-07-31 09:06:00,09:06:00,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,NaN,NaN,No,NaN,111,Cash,41,3.6,3.8,https://cdn-icons-png.flaticon.com/128/11409/1...
103020,2024-07-31 15:12:00,15:12:00,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,NaN,NaN,No,NaN,1097,UPI,17,4.3,3.3,https://cdn-icons-png.flaticon.com/128/16526/1...
103021,2024-07-31 13:59:00,13:59:00,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,NaN,NaN,No,NaN,2201,Cash,37,3.6,3.2,https://cdn-icons-png.flaticon.com/128/9983/99...
103022,2024-07-31 14:56:00,14:56:00,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,NaN,NaN,No,NaN,267,UPI,47,3.4,3.1,https://cdn-icons-png.flaticon.com/128/6839/68...
103023,2024-07-31 13:57:00,13:57:00,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,NaN,NaN,No,NaN,462,UPI,3,4.8,4.4,https://cdn-icons-png.flaticon.com/128/16526/1...

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[us]
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  str
 3   Booking_Status              103024 non-null  str
 4   Customer_ID                 103024 non-null  str
 5   Vehicle_Type                103024 non-null  str
 6   Pickup_Location             103024 non-null  str
 7   Drop_Location               103024 non-null  str
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   str
 11  Canceled_Rides_by_Driver    18434 non-null   str
 12  Incomplete_Rides            63967 non-null   str
 13  Incomplete_Rides_Reason     3926 non-null    str
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   str
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              103024 non-null  str
dtypes: datetime64[us](1), float64(4), int64(2), object(1), str(12)
memory usage: 15.7+ MB

In [7]:
df["V_TAT"] = df["V_TAT"].fillna(0)

In [8]:
df["V_TAT"]= pd.to_numeric(df["V_TAT"], errors="coerce")

In [9]:
df["C_TAT"] = df["C_TAT"].fillna(0)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[us]
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  str
 3   Booking_Status              103024 non-null  str
 4   Customer_ID                 103024 non-null  str
 5   Vehicle_Type                103024 non-null  str
 6   Pickup_Location             103024 non-null  str
 7   Drop_Location               103024 non-null  str
 8   V_TAT                       103024 non-null  float64
 9   C_TAT                       103024 non-null  float64
 10  Canceled_Rides_by_Customer  10499 non-null   str
 11  Canceled_Rides_by_Driver    18434 non-null   str
 12  Incomplete_Rides            63967 non-null   str
 13  Incomplete_Rides_Reason     3926 non-null    str
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   str
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              103024 non-null  str
dtypes: datetime64[us](1), float64(4), int64(2), object(1), str(12)
memory usage: 15.7+ MB

In [11]:
df["Canceled_Rides_by_Customer"] = df["Canceled_Rides_by_Customer"].fillna("NaN")

In [12]:
df["Canceled_Rides_by_Driver"] = df["Canceled_Rides_by_Driver"].fillna("NaN")

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[us]
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  str
 3   Booking_Status              103024 non-null  str
 4   Customer_ID                 103024 non-null  str
 5   Vehicle_Type                103024 non-null  str
 6   Pickup_Location             103024 non-null  str
 7   Drop_Location               103024 non-null  str
 8   V_TAT                       103024 non-null  float64
 9   C_TAT                       103024 non-null  float64
 10  Canceled_Rides_by_Customer  103024 non-null  str
 11  Canceled_Rides_by_Driver    103024 non-null  str
 12  Incomplete_Rides            63967 non-null   str
 13  Incomplete_Rides_Reason     3926 non-null    str
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   str
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              103024 non-null  str
dtypes: datetime64[us](1), float64(4), int64(2), object(1), str(12)
memory usage: 15.7+ MB

In [14]:
# Ab hum baki columns me jo null values hain unhe ek sath fill karenge

df = df.fillna({
    "Incomplete_Rides" : "NaN",
    "Incomplete_Rides_Reason" : "NaN",
    "Payment_Method" : "NaN",
    "Driver_Ratings" : 0,
    "Customer_Rating" : 0
})

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[us]
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  str
 3   Booking_Status              103024 non-null  str
 4   Customer_ID                 103024 non-null  str
 5   Vehicle_Type                103024 non-null  str
 6   Pickup_Location             103024 non-null  str
 7   Drop_Location               103024 non-null  str
 8   V_TAT                       103024 non-null  float64
 9   C_TAT                       103024 non-null  float64
 10  Canceled_Rides_by_Customer  103024 non-null  str
 11  Canceled_Rides_by_Driver    103024 non-null  str
 12  Incomplete_Rides            103024 non-null  str
 13  Incomplete_Rides_Reason     103024 non-null  str
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              103024 non-null  str
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              103024 non-null  float64
 18  Customer_Rating             103024 non-null  float64
 19  Vehicle Images              103024 non-null  str
dtypes: datetime64[us](1), float64(4), int64(2), object(1), str(12)
memory usage: 15.7+ MB

In [16]:
# Dirty Values - N/A, NULL, Blank, spaces

df.replace(                                                 # Data me ["N/A", "NULL", "", " "] ye values jaha bhi hongi unhe "NAN" matlab "Blank" se replace kar dega
    ["N/A", "NULL", "", " "], np.nan, inplace=True          # Ye kiya taki kahi koi null ya blank space bach na jaye
)

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,0.0,0.0,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,0.0,0.0,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,0.0,0.0,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,0.0,0.0,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,2024-07-31 09:06:00,09:06:00,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,NaN,NaN,No,NaN,111,Cash,41,3.6,3.8,https://cdn-icons-png.flaticon.com/128/11409/1...
103020,2024-07-31 15:12:00,15:12:00,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,NaN,NaN,No,NaN,1097,UPI,17,4.3,3.3,https://cdn-icons-png.flaticon.com/128/16526/1...
103021,2024-07-31 13:59:00,13:59:00,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,NaN,NaN,No,NaN,2201,Cash,37,3.6,3.2,https://cdn-icons-png.flaticon.com/128/9983/99...
103022,2024-07-31 14:56:00,14:56:00,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,NaN,NaN,No,NaN,267,UPI,47,3.4,3.1,https://cdn-icons-png.flaticon.com/128/6839/68...
103023,2024-07-31 13:57:00,13:57:00,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,NaN,NaN,No,NaN,462,UPI,3,4.8,4.4,https://cdn-icons-png.flaticon.com/128/16526/1...

In [17]:
df.isnull().sum()                   # Kahi koi null value nahi he

Date                          0
Time                          0
Booking_ID                    0
Booking_Status                0
Customer_ID                   0
Vehicle_Type                  0
Pickup_Location               0
Drop_Location                 0
V_TAT                         0
C_TAT                         0
Canceled_Rides_by_Customer    0
Canceled_Rides_by_Driver      0
Incomplete_Rides              0
Incomplete_Rides_Reason       0
Booking_Value                 0
Payment_Method                0
Ride_Distance                 0
Driver_Ratings                0
Customer_Rating               0
Vehicle Images                0
dtype: int64

In [18]:
df = df.apply(lambda x : x.str.strip().str.title() if x.dtype == "String" else x)       # Taki kahi extra ya unwanted space ho to hatjaye or cells ke andar j bhi string likha he wo "Title" wale format me ho jaye

In [19]:
df["Pickup_Location"].value_counts()

Pickup_Location
Banashankari            2201
Yeshwanthpur            2139
RT Nagar                2135
Indiranagar             2133
Sahakar Nagar           2126
Basavanagudi            2120
Ramamurthy Nagar        2116
Vijayanagar             2113
Tumkur Road             2105
Cox Town                2100
Magadi Road             2099
BTM Layout              2091
Hennur                  2090
Whitefield              2087
Mysore Road             2085
Kengeri                 2083
Nagarbhavi              2083
Langford Town           2079
Hosur Road              2074
Kammanahalli            2071
Sarjapur Road           2070
Peenya                  2069
Majestic                2067
Koramangala             2062
KR Puram                2058
Malleshwaram            2058
Hebbal                  2058
Frazer Town             2048
MG Road                 2048
Bannerghatta Road       2046
Electronic City         2044
Yelahanka               2044
HSR Layout              2042
Richmond Town           2042
JP Nagar                2039
Ulsoor                  2038
Rajarajeshwari Nagar    2037
Hulimavu                2030
Marathahalli            2027
Shivajinagar            2017
Varthur                 2013
Shantinagar             2012
Bellandur               2008
Padmanabhanagar         2004
Kadugodi                2002
Devanahalli             1999
Chickpet                1994
Jayanagar               1985
Chamarajpet             1981
Rajajinagar             1952
Name: count, dtype: int64

In [20]:
df.describe()

,Date,V_TAT,C_TAT,Booking_Value,Ride_Distance,Driver_Ratings,Customer_Rating
count,103024,103024.000000,103024.000000,103024.000000,103024.000000,103024.000000,103024.000000
mean,2024-07-16 11:31:38.879678,106.096502,52.697381,548.751883,14.189927,2.481997,2.482529
min,2024-07-01 00:00:00,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000
25%,2024-07-08 18:41:00,0.000000,0.000000,242.000000,0.000000,0.000000,0.000000
50%,2024-07-16 11:23:00,84.000000,45.000000,386.000000,8.000000,3.400000,3.400000
75%,2024-07-24 05:18:00,196.000000,95.000000,621.000000,26.000000,4.200000,4.200000
max,2024-07-31 23:58:00,308.000000,145.000000,2999.000000,49.000000,5.000000,5.000000
std,NaN,104.532203,50.005090,536.541221,15.776270,1.991983,1.992770

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[us]
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  str
 3   Booking_Status              103024 non-null  str
 4   Customer_ID                 103024 non-null  str
 5   Vehicle_Type                103024 non-null  str
 6   Pickup_Location             103024 non-null  str
 7   Drop_Location               103024 non-null  str
 8   V_TAT                       103024 non-null  float64
 9   C_TAT                       103024 non-null  float64
 10  Canceled_Rides_by_Customer  103024 non-null  str
 11  Canceled_Rides_by_Driver    103024 non-null  str
 12  Incomplete_Rides            103024 non-null  str
 13  Incomplete_Rides_Reason     103024 non-null  str
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              103024 non-null  str
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              103024 non-null  float64
 18  Customer_Rating             103024 non-null  float64
 19  Vehicle Images              103024 non-null  str
dtypes: datetime64[us](1), float64(4), int64(2), object(1), str(12)
memory usage: 15.7+ MB

In [22]:
df

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,0.0,0.0,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,0.0,0.0,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,0.0,0.0,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,0.0,0.0,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,2024-07-31 09:06:00,09:06:00,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,NaN,NaN,No,NaN,111,Cash,41,3.6,3.8,https://cdn-icons-png.flaticon.com/128/11409/1...
103020,2024-07-31 15:12:00,15:12:00,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,NaN,NaN,No,NaN,1097,UPI,17,4.3,3.3,https://cdn-icons-png.flaticon.com/128/16526/1...
103021,2024-07-31 13:59:00,13:59:00,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,NaN,NaN,No,NaN,2201,Cash,37,3.6,3.2,https://cdn-icons-png.flaticon.com/128/9983/99...
103022,2024-07-31 14:56:00,14:56:00,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,NaN,NaN,No,NaN,267,UPI,47,3.4,3.1,https://cdn-icons-png.flaticon.com/128/6839/68...
103023,2024-07-31 13:57:00,13:57:00,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,NaN,NaN,No,NaN,462,UPI,3,4.8,4.4,https://cdn-icons-png.flaticon.com/128/16526/1...

In [23]:
df["Time"] = pd.to_datetime(df["Time"], format="%H:%M:%S", errors="coerce")

In [24]:
df["Time"].dtype

dtype('<M8[us]')

In [25]:
df

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,1900-01-01 14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,0.0,0.0,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,0.0,0.0,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,1900-01-01 22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,1900-01-01 19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,1900-01-01 03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,0.0,0.0,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,0.0,0.0,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,1900-01-01 09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,2024-07-31 09:06:00,1900-01-01 09:06:00,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,NaN,NaN,No,NaN,111,Cash,41,3.6,3.8,https://cdn-icons-png.flaticon.com/128/11409/1...
103020,2024-07-31 15:12:00,1900-01-01 15:12:00,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,NaN,NaN,No,NaN,1097,UPI,17,4.3,3.3,https://cdn-icons-png.flaticon.com/128/16526/1...
103021,2024-07-31 13:59:00,1900-01-01 13:59:00,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,NaN,NaN,No,NaN,2201,Cash,37,3.6,3.2,https://cdn-icons-png.flaticon.com/128/9983/99...
103022,2024-07-31 14:56:00,1900-01-01 14:56:00,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,NaN,NaN,No,NaN,267,UPI,47,3.4,3.1,https://cdn-icons-png.flaticon.com/128/6839/68...
103023,2024-07-31 13:57:00,1900-01-01 13:57:00,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,NaN,NaN,No,NaN,462,UPI,3,4.8,4.4,https://cdn-icons-png.flaticon.com/128/16526/1...

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[us]
 1   Time                        103024 non-null  datetime64[us]
 2   Booking_ID                  103024 non-null  str
 3   Booking_Status              103024 non-null  str
 4   Customer_ID                 103024 non-null  str
 5   Vehicle_Type                103024 non-null  str
 6   Pickup_Location             103024 non-null  str
 7   Drop_Location               103024 non-null  str
 8   V_TAT                       103024 non-null  float64
 9   C_TAT                       103024 non-null  float64
 10  Canceled_Rides_by_Customer  103024 non-null  str
 11  Canceled_Rides_by_Driver    103024 non-null  str
 12  Incomplete_Rides            103024 non-null  str
 13  Incomplete_Rides_Reason     103024 non-null  str
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              103024 non-null  str
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              103024 non-null  float64
 18  Customer_Rating             103024 non-null  float64
 19  Vehicle Images              103024 non-null  str
dtypes: datetime64[us](2), float64(4), int64(2), str(12)
memory usage: 15.7 MB

In [27]:
# Humne dekha ki Booking_Value har jagah dali hui he jabki booking status "Success" ho ya na ho

df["Booking_Value"] = df["Booking_Value"].where(df["Booking_Status"]=="Success", 0)

In [28]:
df

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,1900-01-01 14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,0.0,0.0,NaN,Personal & Car related issue,NaN,NaN,0,NaN,0,0.0,0.0,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,1900-01-01 22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,1900-01-01 19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,1900-01-01 03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,0.0,0.0,Driver is not moving towards pickup location,NaN,NaN,NaN,0,NaN,0,0.0,0.0,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,1900-01-01 09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,2024-07-31 09:06:00,1900-01-01 09:06:00,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,NaN,NaN,No,NaN,111,Cash,41,3.6,3.8,https://cdn-icons-png.flaticon.com/128/11409/1...
103020,2024-07-31 15:12:00,1900-01-01 15:12:00,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,NaN,NaN,No,NaN,1097,UPI,17,4.3,3.3,https://cdn-icons-png.flaticon.com/128/16526/1...
103021,2024-07-31 13:59:00,1900-01-01 13:59:00,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,NaN,NaN,No,NaN,2201,Cash,37,3.6,3.2,https://cdn-icons-png.flaticon.com/128/9983/99...
103022,2024-07-31 14:56:00,1900-01-01 14:56:00,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,NaN,NaN,No,NaN,267,UPI,47,3.4,3.1,https://cdn-icons-png.flaticon.com/128/6839/68...
103023,2024-07-31 13:57:00,1900-01-01 13:57:00,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,NaN,NaN,No,NaN,462,UPI,3,4.8,4.4,https://cdn-icons-png.flaticon.com/128/16526/1...

In [29]:
df.to_csv("Cleaned_Bookings-100000-Rows.xlsx", index=False)

In [30]:
# Connection banayenge ab dataframe ko load karenge mysql me

import pandas as pd
from sqlalchemy import create_engine

In [31]:
pd.read_csv("Cleaned_Bookings-100000-Rows.xlsx")

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,1900-01-01 14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,0.0,0.0,NaN,Personal & Car related issue,NaN,NaN,0,NaN,0,0.0,0.0,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,1900-01-01 22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,1900-01-01 19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,1900-01-01 03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,0.0,0.0,Driver is not moving towards pickup location,NaN,NaN,NaN,0,NaN,0,0.0,0.0,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,1900-01-01 09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,2024-07-31 09:06:00,1900-01-01 09:06:00,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,NaN,NaN,No,NaN,111,Cash,41,3.6,3.8,https://cdn-icons-png.flaticon.com/128/11409/1...
103020,2024-07-31 15:12:00,1900-01-01 15:12:00,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,NaN,NaN,No,NaN,1097,UPI,17,4.3,3.3,https://cdn-icons-png.flaticon.com/128/16526/1...
103021,2024-07-31 13:59:00,1900-01-01 13:59:00,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,NaN,NaN,No,NaN,2201,Cash,37,3.6,3.2,https://cdn-icons-png.flaticon.com/128/9983/99...
103022,2024-07-31 14:56:00,1900-01-01 14:56:00,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,NaN,NaN,No,NaN,267,UPI,47,3.4,3.1,https://cdn-icons-png.flaticon.com/128/6839/68...
103023,2024-07-31 13:57:00,1900-01-01 13:57:00,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,NaN,NaN,No,NaN,462,UPI,3,4.8,4.4,https://cdn-icons-png.flaticon.com/128/16526/1...

In [32]:
engine = create_engine("mysql+pymysql://root:Sunny%402838@localhost:3306/ola")

In [33]:
df.to_sql(name="ola_data", con=engine, if_exists="replace", index=False)

103024